### ISSUE TITLE
G1 build missing header files UnionAfx.h

### ISSUE THREAD

**Issue by Maciej-GBS** [Gratt-5r2/zGamePad#3]
Hello,
Can you help resolve the issue below? These files do not exist, should I somehow link the project with the UnionProject to make it work?

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "SystemPack\Union.Patch\CPatchFile.h"	zGamePad	zGamePad\zGamePad\UnionAfx.h	71	
Error (active)	E1696	cannot open source file "Memory\Shw32.h"	zGamePad	zGamePad\zGamePad\UnionAfx.h	35	
Error (active)	E1696	cannot open source file "Common\Common.h"	zGamePad	zGamePad\zGamePad\UnionAfx.h	40	
Error (active)	E1696	cannot open source file "Core\Core.h"	zGamePad	zGamePad\zGamePad\UnionAfx.h	55	
Error (active)	E1696	cannot open source file "Vdfs\Vdfs.h"	zGamePad	zGamePad\zGamePad\UnionAfx.h	63

**Comment by Gratt-5r2** [comment]
Hi, this is Union SDK headers.
Your should install SDK **1.0L** from the [Resource manager](https://worldofplayers.ru/threads/41415/) or [GDrive](https://drive.google.com/drive/folders/1IY-fFXdkmOfl9HqKWUGCEBuKeaSjoWJ9?usp=sharing).

**Comment by Maciej-GBS** [comment]
Thanks
